services:
  # for development purposes
  dev:
    build: .
    # uncomment the following lines if you want to modify user parameters
    # without rebuilding the image every time

    volumes:
      - ./data:/data
      - ./:/code/

    environment:
      - KBC_DATADIR=/data
